# This message details the Obstacles Status Msg

nepi_interfaces/ProcessStatus process_status

string controls_topic

float32 min_range_m
float32 max_range_m

bool has_navpose
string navpose_topic
bool navpose_topic_connected

bool has_color_image
string color_image_topic
bool color_image_topic_connected

bool full_screen_enabled

bool show_sources_enabled
bool show_ground_enabled
bool show_obstacles_enabled
